### ISSUE TITLE
Create simple chatbot completions

### ISSUE THREAD

**Issue by nightcrazy23** [darth-mark-23/carousel#1]
# Create simple chatbot completions

## Preamble

In order to get the initial Interpreter & Code Generator up and running, we need completions. This ticket will only cover a very basic scenario in the console; future tickets will start to build out the html generation.

## Summary

Create a script that runs in the console that is capable of generating chat completions.

## Requirements.

1. User can type input.
2. A chat completion is returned.

**Comment by darth-mark-23** [comment]
Need to add tests for the new code. Whoops. Creating a new ticket to address this.
